### PR TITLE
win now shows after everything is loaded; no white empty box anymore

### PR DESCRIPTION
**Pull request by wabosh**
adding `show: false` to the window options & calling `win.show()` on `did-finish-load` makes the window wait until everything is loaded.

### CODE REVIEW

**Comment by OrangeNote** [comment]
Hi there!

I don't know if this change is good or bad, because RuneBook is pretty slow at loading window contents so it takes a few seconds to be fully operational. While it is a good thing from an esthetic perspective to show the window only when it's ready, I don't think it's a good thing for the overall user experience, because launching it takes more than expected (apparently); instead, showing the empty window as a placeholder might help reducing the perceived waiting time.

That being said, what's your main motivation behind this proposed change?

**Comment by angeldeejay** [comment]
I've committed this already on my pull request. It was a truly bug

**Comment by wabosh** [comment]
Ok, not seeing anything for a longer time is not that nice too. But what about a small loading window?
My problem is, that whenever i launch the program, it really feels like a website, which it shouldn't in my opinion. When you start seeing the ui come up, it also takes some time until everything is ready.

**Comment by OrangeNote** [comment]
What about a [splash screen](https://wikipedia.org/wiki/Splash_screen) with the RuneBook logo?

**Comment by wabosh** [comment]
Splashscreen is now added to my master branch.

**Pull request merged**
