### PR TITLE
Full translation + language picker on settings

### PR DESCRIPTION
**Pull request by angeldeejay**
- Full translation to the whole project (labels, texts, tooltips, placeholders, titles, tabs)
- Fixed settings modal distribution
- Added lang param on settings and config file to store
- Language change is reflected immediately

Initially in spanish and english but can be added more languages to `src/locales`

### Initial state
settings_en
### Language dropdown view
settings_es
### Spanish translated main view
image

### CODE REVIEW

**Comment by OrangeNote** [comment]
Hi, thank you for this awesome contribution! I'm going to let the community know about this new feature so we can bring in more languages before next major release.

**Comment by OrangeNote** [comment]
For the Spanish translation, at `settings.client_path` I would keep `League Client` instead of `cliente de League of Legends` because my intent is to distinguish the `League of Legends` executable (basically the **launcher**) from the actual **client** executable `League Client`. This is important because users have to select the right executable, that is the **client**, if they choose to manually set the path.

**Comment by angeldeejay** [comment]
No problem, but you should leave it as `LeagueClient` (as filename), because in spanish is confusing the use of `League Client` (separated words) to refer to `LeagueClient.exe` file

**Comment by OrangeNote** [comment]
I agree.

Also I would put the language dropdown under Settings instead of Advanced. The advanced section is for special settings with a specific intent (aka if you don't know what it is then you don't need it).

**Comment by angeldeejay** [comment]
No problem

**Comment by angeldeejay** [comment]
What about this?

image

**Comment by OrangeNote** [comment]
Good. I'll merge the pull request soon.

I need to test if it works when compiled too, then we're ready to go. Also are you on Windows or Mac?

**Comment by angeldeejay** [comment]
I've compiled without problems on Windows and Linux, so I guess Mac is compiling too

**Comment by OrangeNote** [comment]
@angeldeejay we missed one quote... how would you say `Unlink this page` in Spanish? `Unlink` here means "remove the reference to".

**Comment by angeldeejay** [comment]
Should be "Desmarcar esta página" or maybe the same meaning as "Remover de páginas locales" (Unlink from local pages)

**Pull request merged**
